name: Sync main with latest upstream W1 branch

on:
  schedule:
    # Every night at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # we need full history
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git identity
        run: |
          git config user.name  "bc-w1-bot"
          git config user.email "bc-w1-bot@users.noreply.github.com"

      - name: Ensure script is executable
        run: chmod +x .github/scripts/update_main_from_w1.sh

      - name: Sync main from upstream
        run: |
          ./.github/scripts/update_main_from_w1.sh